### ISSUE TITLE
layer-swipe-js not support arcgis js api 3.18

### ISSUE THREAD

**Issue by dyh333** [Esri/arcgis-dijit-layer-swipe-js#11]
hi, @driskull , this layer-swipe-js seems not support arcgis js api 3.18? 
i found there is a LayerSwipe widget in esri/dijit module in 3.18, but the code is mixed, but i want to update some function to meet my need

**Comment by driskull** [comment]
Hi @dyh333, yes it's supported in 3.18. It just hasn't been updated on GitHub for a while. I'll update the code here.

**Comment by dksgis** [comment]
hi, @driskull , when this layer-swipe-js will support arcgis js api 4.x?

**Comment by driskull** [comment]
@dingkesong there should be a widget in the API at some point to do this but not an external widget on GitHub. I don't have a date for you just yet. sorry!

**Comment by dksgis** [comment]
> @dingkesong there should be a widget in the API at some point to do this but not an external widget on GitHub. I don't have a date for you just yet. sorry!
 thank you
